### ISSUE TITLE
Correct way to extend the package

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/Companies#1]
Hello, I would like to ask what is the correct way to extend the package to add new fields from Enso. I need to add more details for a company but I do not know exactly what is the correct way to do it.

Once again thanks in advance for making our lives easier :)

**Comment by aocneanu** [comment]
The packages were updated and now you can use the config to set 3 params:

```php
    'requestValidator' => null,  // this can be a local form validator
    'formTemplate' => null, // project path to the form template (json)
    'tableTemplate' => null, // project path to the table template (json)
```

If provided, the files from config will override the ones from the package.

The `Company` model already has `protected $guarded = []` so if you create a local migration that will add extra fields the controller will work.

The `CompanyTable` `query()` method brings `companies.*` to the front-end, so whatever you configure in the table template will be used.

@gandesc please update documentation for companies & people with the above.

**Comment by aocneanu** [comment]
I will close this due to inactivity
